services:

    app:
        build: ./pwnedhub
        image: pwnedhub-dev
        expose:
            - 80
        volumes:
            - .:/src
            - ~/tmp:/tmp
        environment:
            - TZ=America/New_York
            - CONFIG=Production
            - DATABASE_HOST=db
            - REDIS_URL=redis://redis:6379/0
            - FLASK_APP=pwnedhub/wsgi.py
        command: gunicorn --workers 10 --bind 0.0.0.0:80 pwnedhub.wsgi:app --error-logfile - --log-level DEBUG
        depends_on:
            - db
            - redis

    sso:
        build: ./pwnedsso
        image: pwnedsso-dev
        expose:
            - 80
        volumes:
            - .:/src
        environment:
            - TZ=America/New_York
            - CONFIG=Production
            - DATABASE_HOST=db
        command: gunicorn --workers 10 --bind 0.0.0.0:80 pwnedsso.wsgi:app --error-logfile - --log-level DEBUG
        depends_on:
            - db

    spa:
        build: ./pwnedspa
        image: pwnedspa-dev
        expose:
            - 80
        volumes:
            - .:/src
        environment:
            - CONFIG=Production
        command: gunicorn --workers 10 --bind 0.0.0.0:80 pwnedspa.wsgi:app --error-logfile - --log-level DEBUG

    api:
        build: ./pwnedapi
        image: pwnedapi-dev
        expose:
            - 80
        volumes:
            - .:/src
        environment:
            - TZ=America/New_York
            - CONFIG=Production
            - DATABASE_HOST=db
            - REDIS_URL=redis://redis:6379/0
            - FLASK_APP=pwnedapi/wsgi.py
        command: gunicorn --workers 1 --worker-class eventlet --bind 0.0.0.0:80 pwnedapi.wsgi:app --error-logfile - --log-level DEBUG
        depends_on:
            - db
            - redis

    api-worker:
        image: pwnedapi-dev
        volumes:
            - .:/src
        environment:
            - TZ=America/New_York
            - CONFIG=Production
            - DATABASE_HOST=db
            - REDIS_URL=redis://redis:6379/0
        command: rq worker -u redis://redis:6379/0 pwnedapi-tasks
        depends_on:
            - db
            - redis

    admin:
        build: ./pwnedadmin
        image: pwnedadmin-dev
        expose:
            - 80
        volumes:
            - .:/src
        environment:
            - TZ=America/New_York
            - CONFIG=Production
            - DATABASE_HOST=db
            - FLASK_APP=pwnedadmin/wsgi.py
        command: gunicorn --workers 10 --bind 0.0.0.0:80 pwnedadmin.wsgi:app --error-logfile - --log-level DEBUG
        depends_on:
            - db

    bot-worker:
        build: ./adminbot
        image: adminbot-dev
        volumes:
            - .:/src
            - ~/tmp:/tmp
        command: rq worker -u redis://redis:6379/0 adminbot-tasks
        depends_on:
            - redis

    proxy:
        image: nginx:alpine
        ports:
            - 80:80
        networks:
            default:
                aliases:
                    - www.pwnedhub.com
                    - sso.pwnedhub.com
                    - test.pwnedhub.com
                    - api.pwnedhub.com
                    - admin.pwnedhub.com
        volumes:
            - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./proxy/proxy_params:/etc/nginx/proxy_params:ro
        depends_on:
            - app
            - sso
            - spa
            - api
            - admin

    db:
        image: mysql
        environment:
            - MYSQL_ROOT_PASSWORD=adminpass
        volumes:
            - ./database/init:/docker-entrypoint-initdb.d:ro

    redis:
        image: redis
