name: Semgrep

on:
  push:

jobs:
  semgrep:
    name: Semgrep SAST scan
    runs-on: ubuntu-latest

    container:
      image: semgrep/semgrep

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
        with:
          path: ./code

      - name: Run Semgrep scan
        # `--error` for failure exit code
        # `--severity ERROR` for highs and criticals
        run: semgrep scan --config auto --sarif ./code > semgrep-report.sarif

      - name: Upload Semgrep artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: semgrep-findings
          path: semgrep-report.sarif
        #if: always()
